### ISSUE TITLE
AceKard theme issues and requests.

### ISSUE THREAD

**Issue by YYoshi241** [RocketRobz/TWiLightMenu#203]
DSi homebrew: says 'launch dsiware with unlaunch hold x for 2 sec.' ON 3ds. Worst, it deleted my homebrew and launched Godmode9 when I did this. On 3ds this message probably shouldn't show up.

Slot 1 icon in upper right corner. Touching it doesn't work.

Start menu: should have GBARunner2 in it. Maybe also slot1. 

Some icons appear glitched. Similar effect to scrolling in older versions. Except it always occurs.

Add option for DSi Menu sound (don't really care if implemented. Just thought I'd mention it)

Acekard and 3ds/DSi theme specific settings should only show when those are selected.

Note: I'm using latest dsimenu++ and launched on my 3ds XL, luma 9.1.

**Comment by YYoshi241** [comment]
By ds homebrew I meant dsi homebrew with .nds extension.
Loading is fine on DSi theme. 
3ds can't use unlaunch so don't know why it thinks that's needed or how dsi homebrew = dsiware (it doesn't)

**Comment by YYoshi241** [comment]
It also generates bootthis.dsi file

**Comment by Epicpkmn11** [comment]
I don't think that DSi homebrew glitch is happening anymore, and I don't get glitched icons so that's probably not happening anymore either.
Is the slot-1 icon supposed to do something when clicked? it looks like it's supposed to be a read/write activity indicator when copying from what I can tell... (but I don't actually have a real Acekard/R4 with wood)
The real akmenu doesn't have game launching in the start menu, so I think GBARunner2 would be rather out of place there... you can just launching it from the top level menu anyways.

Should this Issue be closed? The problems brought up in it are solved by now, but I guess maybe it should stay as a feature request.
