### ISSUE TITLE
DSImenu++ not booting after latest update

### ISSUE THREAD

**Issue by 0klux** [RocketRobz/TWiLightMenu#213]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ x]  Release _[please specify version]_ 
2.0.2
- [ ]  Nightly _[insert here commit hash]_

### DSiMenu++ version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
6.2.1
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Dsimenu++ should boot as normal

### Actual behaviour

Dsimenu++ freezes on a top black screen and bottom white screen after updating. I can't even boot the last-ran rom through launcher. (Should mention that when using last-ran rom, before freeziing, the app tries to create a new save file

### Steps to reproduce

1.Just boot dsimenu++
2.
3.

**Comment by Robz8** [comment]
Try reinstalling the latest CIAs.

**Comment by 0klux** [comment]
Already tried.
And just an update, after copying a clean _nds folder from the release and moving the old one to another folder, i was able to boot into dsimenu++. But after changing the settings, the problem returned. The settings i changed were:

Gui Settings
Last played - yes 
dsimenu logo - hide
Box art - hide
use 12 hour - no

Games and apps settings
Language - japanese
Arm9 cpu speed - TWL
Vram boost - on
Slot 1 launch method - direct
sound/mic frequency - 47.61 khz

**Comment by dmsummers** [comment]
Using v6.4.3 on o3dsxl (With Luma)
Launcher v2.1.0
Upgraded from DSiMenu++ v5.4.1

I had the same issue.

Removing my settings.ini and letting TWiLightMenu generate a new one solved the issue.
Setting AUTORUNGAME to 1 caused it to return
Setting it to 0, then launching a game, then setting AUTORUNGAME back to 1 worked
Afterwards, setting LAUNCH_TYPE to 1 (from 0)  in a new automatically generated settings.ini also worked
Using my old settings.ini as is worked at this point as well

I'm not really sure how TWiLightMenu knows which game I played last, but maybe it changed since 5.4.1. I'm also not sure what LAUNCH_TYPE does, but in a fresh settings.ini, it's 0 and in settings.ini after launching a game, it's 1.

Hope this helps with figuring out the root problem.
