### ISSUE TITLE
Autoboot NTR Cartridge

### ISSUE THREAD

**Issue by DeckOfNoobs** [RocketRobz/TWiLightMenu#232]
TWiLight Menu++ offers more performance-boosting options than NTR Launcher does; it's probably just a me-thing but it'd be nice to have an option to autoboot the cartridge if, say, a button is held.

**Comment by lenix9090** [comment]
Yes! For example, with the SELECT button

PD: Google Translate

**Comment by Valkristh** [comment]
If you have (DSi) unlaunch press B

**Comment by NightYoshi370** [comment]
I don't think this is the scope of TWiLightMenu++

**Comment by FlameKat53** [comment]
I believe if you name slot1launch.srldr to main.srldr it will autoboot the game, but you will need to manually change the name back if you want to go back to using TWiLight menu++ after having tried out what I described above

**Comment by NightYoshi370** [comment]
Wait, really?
If so, I guess autobooting NTR cartridges could be made a setting.
We could already use the start button to take us to the settings where we can revert the change

**Comment by FlameKat53** [comment]
naming anything main.srldr and using boot.nds (or launching the TWiLight menu++ cia) will result in it being launched because TWLMenu just boots Main.srldr, if you name MKDS.nds to Main.srldr it would likely error out. But iirc Robz said .nds homebrew that are dsi headered can be launched without nds-bootstrap, so any dsi headered homebrew *should* in theory work

**Comment by RocketRobz** [comment]
To autoboot an NTR cartridge, turn on the feature that starts the last-ran ROM in TWLMenu++ settings, and then launch Slot-1.
The next time TWLMenu++ is started, Slot-1 will boot.
