### ISSUE TITLE
tried an ap patch out of usrcheat.dat didnt work

### ISSUE THREAD

**Issue by MarioMasta64** [RocketRobz/TWiLightMenu#369]
applied ap patch for pokemon soul silver (with cheat code) and it just makes it white screens now

**Comment by piratesephiroth** [comment]
(this is an issue of nds-bootstrap, not TWiLight Menu)

These codes are originally made for flashcards and their kernels reserve small sections of RAM just for storing the blocks of code generated by the patch.

nds-bootstrap doesn't particularly care about that so codes like that just won't work because they will try to use a space of memory that it's already being used by the homebrew.

**Comment by MarioMasta64** [comment]
so then is it possible to adapt these codes this to work with nds bootstrap? and wouldnt that make it so 90% of codes dont work anymore?

**Comment by FM1337** [comment]
> so then is it possible to adapt these codes this to work with nds bootstrap? and wouldnt that make it so 90% of codes dont work anymore?

I think you hit the nail on the head.

**Comment by NightYoshi370** [comment]
As this is irrelevant to TWiLightMenu++, I'll be closing this. Please use the nds-bootstrap repo if you'd like to continue
