### ISSUE TITLE
Error with sleep while in game

### ISSUE THREAD

**Issue by rogueangel2k** [RocketRobz/TWiLightMenu#470]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Close the lid, while in game, console and game should go to sleep.

### Actual behaviour

Close the lid, and using "New Super Mario Bros." as an example game, the game's audio of "Bye bye" when lid closes and "It's me Mario" loops like this... "Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario... Bye bye... It's me Mario..." Endlessly. Opening the lid brings you back into the game as expected. The console's lights never go into the sleep mode pattern. They remain illuminated and not blinking. I have tested with other games, such as Teenage Mutant Ninja Turtles 3 - Mutant Nightmare by Konami with the same results except this game doesn't make a distinct sound when closing or opening the lid.

### Steps to reproduce

1. Open Twilight Menu ++
2. Choose Game
3. Close / Open lid.

**Comment by NightYoshi370** [comment]
This is an issue with nds-bootstrap, not TWiLightMenu++

**Comment by rogueangel2k** [comment]
So, what am I to do about it then? How about an answer instead of fucking closing the thread.

**Comment by Stack3r** [comment]
You need to watch your language

**Comment by NightYoshi370** [comment]
Make an issue on the nds-bootstrap repository.

**Comment by JeodC** [comment]
Unable to reproduce using ntr-forwarder and TWL++ on latest bootstrap release and latest nightly. Please ensure you have the latest versions (v0.17.1 for bootstrap release).

**Comment by rogueangel2k** [comment]
You guys provide a way to download and upgrade nds-bootstrap in your software. You are responsible for answering questions about that issue. I code software all day and if .net issues an update that breaks my software, I can't just tell my end users "you need to deal with Microsoft". It doesn't work that way. That's support 101 homie, and apologies on the language but it's not as cut and dried of an issue as you want it to be. You're being very, very dismissive.

I am using the "Release" version via the button that is provided inside of Twilight Menu ++ Updater.

**Comment by piratesephiroth** [comment]
No one is obliged to provide anything to you here.

TWiLightMenu is a frontend to nds-bootstrap and each is a different project and has its own repository.
It's nobody's fault that you're mentally handicapped and can't read.

**Comment by rogueangel2k** [comment]
I see. What a fool. Love, peace, and chicken grease. Enjoy your small penis.

**Comment by rogueangel2k** [comment]
I see. What a shame. What a fool.

**Comment by NightYoshi370** [comment]
> You guys provide a way to download and upgrade nds-bootstrap in your software.
Not in this software. That's a TWiLightMenu++ Updater issue, and we would redirect you to make an issue there.

Dude, why are you being so stubborn? Just make an issue in the nds-bootstrap github repository like everyone else. If you do that, I (and I mean myself) would be more than glad to help you out.

Just to explain stuff further:
- TWiLightMenu++: Frontend for flashcards, nds-bootstrap and a unified interface for Gameboy, Genesis, DS, NES, SNES, etc roms
- nds-bootstrap: ds roms loaded on an sd card.

See, twilight isn't just about ds. That's why we have individual areas for each loader, and why we push so hard for organization.

**Comment by NightYoshi370** [comment]
> It's nobody's fault that you're mentally handicapped and can't read.

No need to insult him though

**Comment by rogueangel2k** [comment]
> > You guys provide a way to download and upgrade nds-bootstrap in your software.
> > Not in this software. That's a TWiLightMenu++ Updater issue, and we would redirect you to make an issue there.
> 
> Dude, why are you being so stubborn? Just make an issue in the nds-bootstrap github repository like everyone else. If you do that, I (and I mean myself) would be more than glad to help you out.
> 
> Just to explain stuff further:
> 
> * TWiLightMenu++: Frontend for flashcards, nds-bootstrap and a unified interface for Gameboy, Genesis, DS, NES, SNES, etc roms
> * nds-bootstrap: ds roms loaded on an sd card.
> 
> See, twilight isn't just about ds. That's why we have individual areas for each loader, and why we push so hard for organization.

I will.

**Comment by NightYoshi370** [comment]
> I will.

There we go. Let me know when you made the nds-bootstrap issue.
If you can't find the repository, let me know as well; I'll link it for you.

**Comment by JeodC** [comment]
The big difference here is that homebrew is created and released for free. You're not paying for the product, so you're not entitled to "excellent customer service". If you're rude, expect to be treated the same way.

TWL++ and Bootstrap are a partnership, not one and the same. The reason TWL++ Updater has a Bootstrap button in it is because TWL++ is a frontend loader for NDS games--it's for ease of access.

That said, when you make your new issue, keep in mind: I couldn't replicate it, and I'm on the same system and CFW you are. We'll need some more info to narrow this down. I suggest adding the following information:

1. That you use the releases provided by TWL++ Updater (this should be a checkbox like the other options in the template tbh since it's live now)

2. Which level/part of the NSMB game you were in when you had the issue

3. Your SD card size and allocation size

**Comment by chyyran** [comment]
> You guys provide a way to download and upgrade nds-bootstrap in your software. You are responsible for answering questions about that issue. I code software all day and if .net issues an update that breaks my software, I can't just tell my end users "you need to deal with Microsoft". It doesn't work that way. That's support 101 homie,

Please recall the terms under which the software was licensed to you. In particular the following clause:

> **THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.** IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Should you disagree with the terms of the license you may negotiate with the copyright holders a more agreeable license under which to use this software, or otherwise cease your use of the software.
