### ISSUE TITLE
Add categories mode for title/rom sorting

### ISSUE THREAD

**Issue by billy-acuna** [RocketRobz/TWiLightMenu#96]
Folder sorting works, but I kinda feel uncomfortable with the all SD access on a DSi Menu replacement, something more cleaner would be a categories mode to navigate between:
- Nintendo DS
- Homebrew
- DSiWare
- Nintendo Entertainment System
- Game Boy
- Game Boy Color
- Favorites, maybe (?

A way create your own categories vía a INI or something else would be ideal.

**Comment by RS55** [comment]
Someone who understands me, having only access to DSiware and DS linked to ALL (gb and nes...) is not comfortable. Since up and down the D-pad is only used to toggle between DSiware and DS you should add as it was before the last updates of SRLoader that were nes, gb (c) and nds.

If this is done it would be ideal to add somewhere, for example: up goes to DSiware and down to NES, being in NDS, which would mean that you should press twice (any, up or down) to go to GB

That's my idea about it to collaborate :P

**Comment by NightYoshi370** [comment]
This is implemented within the latest commit. Closing

**Comment by rodrigost23** [comment]
Is it really the same thing? I thought the commit you mentioned was a global setting to show/hide the ROM types. The suggestion here is to filter them while already on the roms folder, instead of having to navigate in and out of folders. Also, having all roms in the same list may not be very comfortable to use for some.
